apiVersion: v1
kind: PersistentVolume
metadata:
  name: phabricator-conf-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /home/data/phabricator-confvol
    server: master1.ceyes.os
